### ISSUE TITLE
书本勘误 101书面 3.7.3章节

### ISSUE THREAD

**Issue by izyForever** [Manistein/let-us-build-a-lua-interpreter#4]
“读者可以参考C03/dummylua-3工程中的common/lualexer.h 和 common/lualexer.c”
代码实际是在compiler目录下，根据前文关于目录结构的介绍，也应该放在compiler目录下合理些

**Comment by Manistein** [comment]
代码是放到compiler目录下的，此处路径写错了，感谢指正。
