### ISSUE TITLE
书本勘误 141书面 4.2.6.1章节

### ISSUE THREAD

**Issue by izyForever** [Manistein/let-us-build-a-lua-interpreter#5]
图4-9中 根据查找变量的流程描述，_ENV中存放的是d比较合理

**Comment by Manistein** [comment]
该图展示的是内层函数的upvalue列表，b是外层函数的local变量，而b在内层函数首先访问，因此需要将其先放入内层函数的upvalue列表中，所以是b。

**Comment by izyForever** [comment]
是的，应该是b，我想错了233
