### ISSUE TITLE
书本勘误 4.3.2节

### ISSUE THREAD

**Issue by buoutuanzi** [Manistein/let-us-build-a-lua-interpreter#7]
![image](https://github.com/Manistein/let-us-build-a-lua-interpreter/assets/96377696/ebb6d60c-156d-422e-a21a-626d964e44a7)
应该是 fs->ls->dyd->actvar.arr 的索引对应寄存器索引，而非 localvar 索引对应寄存器索引

**Comment by Manistein** [comment]
是的，locvars是不断增加的，这里应该是dyd->actvar->arr的索引表明local变量位于哪个寄存器中。感谢反馈。
